### ISSUE TITLE
在docker-compose中使用此项目？

### ISSUE THREAD

**Issue by felixding** [wi1dcard/v2ray-exporter#8]
你好，我尝试在docker-compose中使用此项目，但v2ray-exporter此时无法启动（不停自动重启），不知道是哪里配置的有问题。

这是我docker-compose.yml中相关的部分：

```
version: "3.4"

services:
  v2ray-exporter:
    image: wi1dcard/v2ray-exporter:master
    ports:
      - 10085:10085
    command: v2ray-exporter --v2ray-endpoint "v2ray:10085" --listen 10085
    restart: always
    links:
      - v2ray
  v2ray:
    image: v2fly/v2fly-core:v4.25.1
    restart: always
    expose:
      - 10085
```
